services:
  - type: web
    name: foodexpress
    plan: free
    startCommand: php -S 0.0.0.0:8000 -t .
    buildCommand: |
      mkdir -p assets/uploads/plats
      mkdir -p assets/uploads/avatars
      chmod 755 assets/uploads
      chmod 755 assets/uploads/plats
      chmod 755 assets/uploads/avatars
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: foodexpress_dakar
      - key: DB_USER
        value: foodexpress_user
      - key: DB_PASS
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        value: FoodExpress Dakar
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Africa/Dakar
